import { ViralFramework, SubtitleStylePreset, BgmTrack } from '@/types';

export const VIRAL_FRAMEWORKS: ViralFramework[] = [
  {
    id: 'super-alimentos',
    name: 'Super Alimentos para tu Órgano',
    badge: '🌟 Pixar 3D · Salud & Curación',
    description: 'Personaje 3D tierno del órgano siendo alimentado con superalimentos, iluminándose y sanando con efectos ASMR.',
    niche: 'Salud, Nutrición Funcional, Fitness & Bienestar',
    targetAudience: 'Personas interesadas en longevidad, nutrición funcional y salud natural',
    icon: 'Sparkles',
    category: 'Salud & Órganos 3D',
    viralScore: 99,
    recommendedScenes: 4,
    allowedDurations: [8],
    requiresSpokenScript: false,
    defaultSceneDuration: 8,
    defaultSubtitleStyle: 'hormozi',
    defaultBgmGenre: 'Upbeat Tech / ASMR',
  },
  {
    id: 'alimentos-que-retan',
    name: 'Alimentos que Retan tu Órgano',
    badge: '⚠️ Pixar 3D · Advertencia & Reto',
    description: 'El órgano recibe alimentos dañinos/chatarra y reacciona cómicamente con inflamación, sudor y fatiga.',
    niche: 'Salud Preventiva, Hábitos, Toxicidad & Dietas',
    targetAudience: 'Audiencia masiva buscando evitar alimentos dañinos e inflamatorios',
    icon: 'Flame',
    category: 'Salud & Órganos 3D',
    viralScore: 98,
    recommendedScenes: 3,
    allowedDurations: [8],
    requiresSpokenScript: false,
    defaultSceneDuration: 8,
    defaultSubtitleStyle: 'bold-yellow',
    defaultBgmGenre: 'Upbeat Tech / ASMR',
  },
  {
    id: 'que-sucede-al-comer',
    name: 'Qué Sucede en tu Cuerpo al Comer...',
    badge: '🔬 Viaje Biológico Cinemático',
    description: 'Recorrido interno paso a paso: entrada por la boca/esófago con zoom-in, estómago, hígado y torrente sanguíneo.',
    niche: 'Biología, Curiosidades Médicas, Ciencia & Viral',
    targetAudience: 'Usuarios curiosos fascinados por cómo reacciona el organismo por dentro',
    icon: 'Eye',
    category: 'Salud & Órganos 3D',
    viralScore: 99,
    recommendedScenes: 4,
    allowedDurations: [7, 8, 10],
    requiresSpokenScript: true,
    defaultSceneDuration: 8,
    defaultSubtitleStyle: 'cyberpunk',
    defaultBgmGenre: 'Cinematic Ambient',
  },
  {
    id: 'organos-frutas',
    name: 'Órganos Comiendo Frutas (Clásico)',
    badge: '🔥 Tendencia Viral 2026',
    description: 'Animaciones 3D hiperrealistas de órganos humanos reaccionando y absorbiendo nutrientes de frutas específicas.',
    niche: 'Salud, Nutrición, Fitness & Biología Curiosa',
    targetAudience: 'Público general 18-45 años buscando bienestar y hacks de salud visuales',
    icon: 'Heart',
    category: 'Salud & Curiosidades',
    viralScore: 97,
    recommendedScenes: 4,
    allowedDurations: [8],
    requiresSpokenScript: false,
    defaultSceneDuration: 8,
    defaultSubtitleStyle: 'hormozi',
    defaultBgmGenre: 'Upbeat Tech / ASMR',
  },
  {
    id: 'fake-podcast',
    name: 'Fake Podcast de Alto Impacto',
    badge: '🎙️ +2.4M Avg Views',
    description: 'Simulación de estudio de podcast profesional con micrófonos Shure y revelaciones contraintuitivas.',
    niche: 'Emprendimiento, Finanzas, Negocios & Mentalidad',
    targetAudience: 'Jóvenes emprendedores, inversores y creadores que consumen clips de valor',
    icon: 'Mic',
    category: 'Negocios & Podcast',
    viralScore: 96,
    recommendedScenes: 4,
    allowedDurations: [6, 8, 10],
    requiresSpokenScript: true,
    defaultSubtitleStyle: 'bold-yellow',
    defaultBgmGenre: 'Dark Phonk / Suspense',
  },
  {
    id: 'rompiendo-mitos',
    name: 'Rompiendo Mitos / El 99% se Equivoca',
    badge: '⚡ Máxima Retención',
    description: 'Frase inicial de choque que destruye una creencia popular y demuestra la verdad científica o lógica.',
    niche: 'Educación, Ciencia, Psicología & Curiosidades',
    targetAudience: 'Personas analíticas y usuarios curiosos en TikTok y Reels',
    icon: 'Zap',
    category: 'Educativo',
    viralScore: 94,
    recommendedScenes: 4,
    allowedDurations: [6, 8, 10],
    requiresSpokenScript: true,
    defaultSubtitleStyle: 'neon-glow',
    defaultBgmGenre: 'Cinematic Ambient',
  },
  {
    id: 'historias-confesiones',
    name: 'Historias & Confesiones Virales',
    badge: '💬 Récord de Comentarios',
    description: 'Narrativas en primera persona con dilemas morales o secretos impactantes con visuales cinemáticos.',
    niche: 'Storytelling, Entretenimiento & Drama',
    targetAudience: 'Audiencia masiva Gen Z / Millennials que busca historias adictivas',
    icon: 'Sparkles',
    category: 'Storytelling',
    viralScore: 95,
    recommendedScenes: 5,
    allowedDurations: [6, 8, 10],
    requiresSpokenScript: true,
    defaultSubtitleStyle: 'cyberpunk',
    defaultBgmGenre: 'Storytelling Lofi',
  },
  {
    id: 'versus-novato-pro',
    name: 'Novato vs Profesional (El Gran VS)',
    badge: '⚔️ Alto Debate',
    description: 'Comparativa visual directa entre cómo lo hace alguien sin experiencia vs un experto en segundos.',
    niche: 'Tecnología, IA, Diseño, Marketing & Fitness',
    targetAudience: 'Personas interesadas en subir de nivel y aprender trucos rápidos',
    icon: 'Split',
    category: 'Comparativa',
    viralScore: 92,
    recommendedScenes: 4,
    allowedDurations: [6, 8, 10],
    requiresSpokenScript: true,
    defaultSubtitleStyle: 'bold-yellow',
    defaultBgmGenre: 'Upbeat Tech',
  },
  {
    id: 'secretos-prohibidos',
    name: 'Herramientas / Secretos Ocultos',
    badge: '🔖 Récord de Guardados',
    description: 'Presentación de hacks o aplicaciones poco conocidas con estética tecnológica y ritmo acelerado.',
    niche: 'Inteligencia Artificial, Software & Productividad',
    targetAudience: 'Creadores y trabajadores digitales buscando atajos y herramientas clave',
    icon: 'Lock',
    category: 'Tech & Hacks',
    viralScore: 97,
    recommendedScenes: 4,
    allowedDurations: [6, 8, 10],
    requiresSpokenScript: true,
    defaultSubtitleStyle: 'neon-glow',
    defaultBgmGenre: 'Dark Synthwave',
  }
];

export const SUBTITLE_PRESETS: Record<string, SubtitleStylePreset> = {
  'hormozi': {
    id: 'hormozi',
    name: 'Alex Hormozi Viral',
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 38,
    textColor: '#FFFFFF',
    highlightColor: '#FACC15',
    backgroundColor: '#000000',
    textShadow: '0 4px 12px rgba(0,0,0,0.9)',
    uppercase: true,
    boxStyle: true,
  },
  'neon-glow': {
    id: 'neon-glow',
    name: 'Cyber Neon Glow',
    fontFamily: 'Inter, sans-serif',
    fontSize: 36,
    textColor: '#FFFFFF',
    highlightColor: '#22D3EE',
    textShadow: '0 0 20px #06B6D4, 0 0 40px #0891B2',
    uppercase: true,
    boxStyle: false,
  },
  'bold-yellow': {
    id: 'bold-yellow',
    name: 'Bold Punchy Yellow',
    fontFamily: 'Impact, sans-serif',
    fontSize: 42,
    textColor: '#FFE600',
    highlightColor: '#FF3B30',
    textShadow: '3px 3px 0px #000000',
    uppercase: true,
    boxStyle: false,
  },
  'minimal-clean': {
    id: 'minimal-clean',
    name: 'Minimal Clean Serif',
    fontFamily: 'system-ui, sans-serif',
    fontSize: 32,
    textColor: '#FFFFFF',
    highlightColor: '#A78BFA',
    textShadow: '0 2px 8px rgba(0,0,0,0.6)',
    uppercase: false,
    boxStyle: false,
  },
  'cyberpunk': {
    id: 'cyberpunk',
    name: 'Cyberpunk Red Box',
    fontFamily: 'Courier New, monospace',
    fontSize: 34,
    textColor: '#FFFFFF',
    highlightColor: '#EC4899',
    backgroundColor: '#EF4444',
    textShadow: '0 2px 10px rgba(0,0,0,0.8)',
    uppercase: true,
    boxStyle: true,
  },
};

export const BGM_TRACKS: BgmTrack[] = [
  {
    id: 'bgm-dark-phonk',
    title: 'Shadow Phonk (Viral TikTok)',
    genre: 'Dark Phonk / Trap',
    url: 'https://assets.mixkit.co/music/preview/mixkit-game-level-music-689.mp3',
    durationSec: 60,
  },
  {
    id: 'bgm-cinematic-suspense',
    title: 'Deep Tension & Discovery',
    genre: 'Cinematic Ambient',
    url: 'https://assets.mixkit.co/music/preview/mixkit-tech-house-vibes-130.mp3',
    durationSec: 60,
  },
  {
    id: 'bgm-lofi-story',
    title: 'Lofi Reflection Chill',
    genre: 'Storytelling Lofi',
    url: 'https://assets.mixkit.co/music/preview/mixkit-chill-bro-494.mp3',
    durationSec: 60,
  },
  {
    id: 'bgm-tech-beat',
    title: 'Digital Future Uplift',
    genre: 'Tech / Upbeat',
    url: 'https://assets.mixkit.co/music/preview/mixkit-raising-me-higher-34.mp3',
    durationSec: 60,
  },
];
